# Generated by Django 4.2.11 on 2024-07-22 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workrecord',
            unique_together={('employee', 'project', 'date')},
        ),
    ]
